name: terraform-validate-tflint-docs

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/aws-vpc-ec2
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform 1.12.2
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Init (sans backend)
        run: terraform init -backend=false

      - name: Format (check)
        run: terraform fmt -check -recursive

      - name: Validate
        run: terraform validate

      - name: Cache TFLint plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('**/.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: TFLint init + lint
        run: |
          tflint --init
          tflint --recursive

  docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: terraform/aws-vpc-ec2
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate terraform docs (inject in README)
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
